# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d736afa3e4c0e08bc5927aa798f76057a5e0ab33a6716f7b845c5825f39d3ae4fb1938890138be62147400a1870d0c69c0cf7443ee9346cce9eab1954fabe9

test:
  secret_key_base: afef968850ca43e5e906dd8b49403a68acc0740abad9f17e42fa9944b1385d30a1f2b296ca05d69dc6309a1291622474f002ac62da7f2d948198a83b8b2f5401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
